### ISSUE TITLE
Incorrect work with Currencies other than SEK

### ISSUE THREAD

**Issue by IlyaSkriblovsky** [Billmate/magento-2-billmate-checkout#123]
Hello!

Thanks for the cool solution! I'm trying to setup Billmate payment method for the site with several localized domains and faced the issue with currencies other than SEK. When I'm trying to make test payment in non-SEK currency payment module seems to always treat order amount as it was in SEK instead of USD/EUR/NOK.

This is the card preview page: all amounts are correct, this item costs 83.7 USD (≈688 SEK)
![image](https://user-images.githubusercontent.com/909638/103489023-64af5980-4e22-11eb-8bcd-3142ec8bd53b.png)

When I click Proceed to Checkout it gets this. Notice that grand total is suddently 83.7 SEK instead of USD. Also notice how order subtotals are incorrectly re-calculated to match amount of 83.7 SEK (≈10 USD).
![image](https://user-images.githubusercontent.com/909638/103489038-83adeb80-4e22-11eb-9028-61bb49386ce5.png)

I didn't found any settings related to supported currencies in installation manual. Does this module supports non-SEK currencies at all? Or may be I just need to upgrade? (I'm running 1.7.9 on Magento 2.3.2)

**Comment by MattiasNilsson** [comment]
@IlyaSkriblovsky Thanks for your feedback! Our solution only support SEK at the moment, but we are in the start phase to add more support for currencies later this year.
