### ISSUE TITLE
UTF8-problem still

### ISSUE THREAD

**Issue by stefanliden** [Billmate/magento-2-billmate-checkout#89]
Our merchant has got utf8 problem on one of their orders in their back office. See picture below
 
The correct one is Öresjögatan 55!

Merchant runs Magento: 2.3.3 PLUGIN: 1.7.0

![image](https://user-images.githubusercontent.com/13320183/94924724-5c135400-04be-11eb-8106-96ee97454b10.png)

**Comment by MaxMalmer** [comment]
Hey! 
The customer should upgrade to the latest version first. There's a patch that might effect this in that patch.
